### ISSUE TITLE
Update Chinese API

### ISSUE THREAD

**Issue by nobodxbodon** [icela/FriceEngine#40]
源自: https://www.zhihu.com/question/263855824/answer/274659265 下的讨论
如果第一步想做到把官方[演示代码](https://github.com/icela/FriceDemo/blob/master/1.7.6/Demo7.java)用到的接口中文化(原有英文接口保留), 请问有何推荐方式? 在下Kotlin盲. 能有commit演示就更感谢了.

**Comment by ice1000** [comment]
请前往 https://github.com/icela/FriceEngine-DSL 讨论。
那个repo有所有的中文API和一个Demo。
中文Demo是up-to-date的。

**Comment by ice1000** [comment]
`/languageE/src` 下面就是代码， `/languageE/test` 下面是Demo。
我个人对于那个中文版本是兴趣性地维护，而且中文API也只有几十行代码。

其实，完全把DSL主仓库里的函数名中文化后，你就可以写中文的FriceEngine代码了。

**Comment by ice1000** [comment]
Java是不能像那样写DSL的，中文代码只能用Kotlin写，而且非常简单。
close issue是因为这个话题不适合在这个repo下讨论 :sweat_smile:
