### ISSUE TITLE
Stupid mistake

### ISSUE THREAD

**Issue by KirCute** [icela/FriceEngine#47]
Stupid mistake in [AttachedObjects](https://github.com/icela/FriceEngine/blob/b93f1cf69fc63da93d8a06e6b4ac5fdf2548f35e/src/org/frice/obj/AttachedObjects.kt).

``` kotlin
fun addObject(vararg objects: T) = objects.forEach { objs.remove(it) }
fun removeObject(vararg objects: T) = objects.forEach { objs.remove(it) }
```

**Comment by ice1000** [comment]
https://github.com/icela/FriceEngine/blob/b93f1cf69fc63da93d8a06e6b4ac5fdf2548f35e/src/org/frice/obj/AttachedObjects.kt#L33
https://github.com/icela/FriceEngine/blob/b93f1cf69fc63da93d8a06e6b4ac5fdf2548f35e/src/org/frice/obj/AttachedObjects.kt#L17

**Comment by ice1000** [comment]
Fixed:

https://github.com/icela/FriceEngine/blob/ec1f00ce07e90cd0516f49e2edf6c5fba000a273/src/org/frice/obj/AttachedObjects.kt#L33
https://github.com/icela/FriceEngine/blob/ec1f00ce07e90cd0516f49e2edf6c5fba000a273/src/org/frice/obj/AttachedObjects.kt#L17

**Comment by ice1000** [comment]
Wow, look at linux kernal.

![](https://user-images.githubusercontent.com/16398479/34079578-416ab53e-e36b-11e7-9628-81a5476b0eee.png)

**Comment by ice1000** [comment]
:sweat_smile:
