### ISSUE TITLE
运行出错了

### ISSUE THREAD

**Issue by dongkuo** [icela/FriceEngine#6]
不懂Kotlin，跑test的时候出现了2个问题：一个是AudioManager.kt的13行和16行编译出错，提示说要在async后加()，加上后编译OK，是Kotlin版本问题？？？二是运行后抛出空指针异常，原因是Game.kt的404行中的panel为空，看panel是在172行初始化的，debug发现压根就没执行这句话，啥情况？？？

**Comment by ice1000** [comment]
好的，反馈已收到，我会去看的。大概一周内可以看到修复(如果问题仅仅是出于我傻逼的话)。
先感谢反馈。

**Comment by ice1000** [comment]
Kotlin版本是个问题，因为我在用Kotlin1.1，我这就改成1.0.7先。
修复问题之后就会close issue，到时候你可以pull。

**Comment by ice1000** [comment]
似乎好了？我这里运行都没问题。我运行了 test/Test2.kt 。
然后我按你说的，async 加了括号，然后改了一下 setBounds 的重载（就是把之前的重载去掉了，避免在初始化之前GG）。现在不知道行不行了。

**Comment by ice1000** [comment]
如果您pull了最近的commit之后还有问题，请等我下周五以后再来修复。。。（学生党对不起啦）

**Comment by dongkuo** [comment]
行，可以了。另外有些demo有问题，你对Game做修改了而demo没跟着修改。PS：弱弱地问一下，你大几？？？

**Comment by ice1000** [comment]
我是高中生

**Comment by ice1000** [comment]
应该是，那你看着弄嘛，早期Demo有些在使用旧API，你可以考虑删除，或者看java doc来使用新API(Frice is well documented！

**Comment by ice1000** [comment]
文档: https://icela.github.io
（方便后来人看）
