### ISSUE TITLE
Revert event for `runLater`

### ISSUE THREAD

**Issue by KirCute** [icela/FriceEngine#61]
rt

**Comment by ice1000** [comment]
> 顺便去掉AttachedObjects的泛型

Created #62 for this.

**Comment by ice1000** [comment]
My solution: create a `setReverted` for `DelayedEvent`.

If you `setReverted(true)`, it will not be executed (if it's still not executed).

**Comment by ice1000** [comment]
Also, I'll remove the getter for the `event` field.
