### ISSUE TITLE
QuadTree split creates subtree at wrong coordinate

### ISSUE THREAD

**Issue by hesslink111** [icela/FriceEngine#82]
https://github.com/icela/FriceEngine/blob/cd9ed30d6fd9471d44021ff73818ab2dd4dd4ff6/src/org/frice/util/QuadTree.kt#L47

Should probably be:
`nodes[2] = QuadTree(level + 1, FQuad(x, y + subHeight, subWidth, subHeight))`

**Comment by ice1000** [comment]
@lfkdsk

**Comment by ice1000** [comment]
Yes, you're right.

**Comment by lfkdsk** [comment]
Yes, you're right. (so old
